apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2021-02-18T18:12:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: classic-rest-service
    app.kubernetes.io/instance: f5
    app.kubernetes.io/part-of: fusion
  name: classic-rest-service-data-claim-f5-classic-rest-service-0
  namespace: default
  resourceVersion: "3009"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/classic-rest-service-data-claim-f5-classic-rest-service-0
  uid: 463f5105-12eb-41e0-87c6-ef52c767c53a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-463f5105-12eb-41e0-87c6-ef52c767c53a
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
