apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2021-02-18T18:26:15Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: classic-rest-service
    app.kubernetes.io/instance: f5
    app.kubernetes.io/part-of: fusion
  name: classic-rest-service-data-claim-f5-classic-rest-service-1
  namespace: default
  resourceVersion: "8843"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/classic-rest-service-data-claim-f5-classic-rest-service-1
  uid: 7b3763e3-e6d8-4b97-9e3a-6d4b7eed6234
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-7b3763e3-e6d8-4b97-9e3a-6d4b7eed6234
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
