apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2021-02-18T18:45:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: connectors-classic
    app.kubernetes.io/instance: f5
    app.kubernetes.io/part-of: fusion
  name: connectors-classic-data-claim-f5-connectors-classic-1
  namespace: default
  resourceVersion: "17139"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/connectors-classic-data-claim-f5-connectors-classic-1
  uid: f35aa10d-cd7d-49c7-b533-55b6861067b8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-7b3763e3-e6d8-4b97-9e3a-6d4b7eed6234
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
