apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2021-02-18T18:12:57Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-west1
    failure-domain.beta.kubernetes.io/zone: us-west1-b
  name: pvc-463f5105-12eb-41e0-87c6-ef52c767c53a
  resourceVersion: "20904"
  selfLink: /api/v1/persistentvolumes/pvc-463f5105-12eb-41e0-87c6-ef52c767c53a
  uid: d9f605aa-af1f-4546-b331-8b5495ab4395
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-fusion-migration-t-pvc-463f5105-12eb-41e0-87c6-ef52c767c53a
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-west1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-west1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Available
