nodeSelector:
  {NODE_POOL}
server:
  ingress:
    enabled: true
  service:
    type: ClusterIP
persistence:
  enabled: true
  type: pvc

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
